# This file was generated by GoReleaser. DO NOT EDIT.
cask "dmarcaid" do
  name "dmarcaid"
  desc "CLI tool for parsing and analyzing DMARC, TLS-RPT, and forensic reports"
  homepage "https://github.com/kidager/dmarcaid"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dmarcaid"

  on_macos do
    on_intel do
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Darwin_x86_64.tar.gz"
      sha256 "8ce453680ac4968aa31c07658c7ea1adecf4a152227c43fdfeefc6d574371b7e"
    end
    on_arm do
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Darwin_arm64.tar.gz"
      sha256 "64ac6295e585426a8c0dc08414ef3baafe5e1220e1993369f15bd3d39659939c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Linux_x86_64.tar.gz"
      sha256 "6643f540a5d46203552ef14c52b43e99aeb0433fa4a347b8c8e0090c52b6124d"
    end
    on_arm do
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Linux_arm64.tar.gz"
      sha256 "e25a7e3396a7bc8b6d200a57c35e9cc04caf5a584890f0e219b00a608296be50"
    end
  end

  # No zap stanza required
end
