# This file was generated by GoReleaser. DO NOT EDIT.
cask "dmarcaid" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "51d72b3ae5660281ae1029d46165589ad33f3bf2ccea3ef021cbae9928b9afb8"
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "33bb11aa24d7f3c6aa5f6687038bd8c91ee7eb4c113e49933f19d00c6530b55f"
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e779342a1c588c7bdf72a035ddb2b80c880a86a5e0adab4f1956c2e4a30b5a41"
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b36058a7e598c4fa228c15dc5f8e4abe409cab1c131c482fe984846eaa8261e5"
      url "https://github.com/kidager/dmarcaid/releases/download/v#{version}/dmarcaid_Linux_arm64.tar.gz"
    end
  end

  name "dmarcaid"
  desc "CLI tool for parsing and analyzing DMARC, TLS-RPT, and forensic reports"
  homepage "https://github.com/kidager/dmarcaid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dmarcaid"

  # No zap stanza required

end
