# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dmarcaid < Formula
  desc "CLI tool for parsing and analyzing DMARC, TLS-RPT, and forensic reports"
  homepage "https://github.com/kidager/dmarcaid"
  version "1.0.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kidager/dmarcaid/releases/download/v1.0.0/dmarcaid_Darwin_x86_64.tar.gz"
      sha256 "c0459b9b715deb649fe41898db7a1b6490ed8829e2c36c841c48710e84fe6d62"

      def install
        bin.install "dmarcaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kidager/dmarcaid/releases/download/v1.0.0/dmarcaid_Darwin_arm64.tar.gz"
      sha256 "eb15537f6b87d87c6feaab69c3ead54ba1b7a9c04dc1f51dfd943efe70bbb9be"

      def install
        bin.install "dmarcaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kidager/dmarcaid/releases/download/v1.0.0/dmarcaid_Linux_x86_64.tar.gz"
      sha256 "e2123ee085f67186a256d8def7e17679b760315f86a1f26458ee099f115f6f23"
      def install
        bin.install "dmarcaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kidager/dmarcaid/releases/download/v1.0.0/dmarcaid_Linux_arm64.tar.gz"
      sha256 "6ed23b2d69688d185aa537856c5f8429c9a681b49d523dac8800724891514066"
      def install
        bin.install "dmarcaid"
      end
    end
  end

  test do
    system "#{bin}/dmarcaid", "version"
  end
end
